"""
배포 준비: PNG→WebP 변환 + text.md gitignore + HTML 경로 업데이트.

Cloudflare Workers(Static Assets)가 master 브랜치의 docs/ 를 자동으로
배포한다. 따라서 이 스크립트는 docs/ 만 master에 commit/push 한다.
(구 gh-pages subtree 방식은 제거됨)

Usage:
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --quality 90    # WebP 품질 (기본 90)
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --dry-run       # 변환 없이 크기 예상만
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --push          # 변환 후 master push (Cloudflare 자동 배포)

단계:
  1. .gitignore에 text.md 추가
  2. papers/*/figures/*.png → *.webp 변환 (quality 90, lossless 아님)
  3. papers/*/index.html, papers/*/review.md에서 .png → .webp 경로 업데이트
  4. {topic}/index.html에서 .png → .webp 경로 업데이트 (figure 참조만, 타임라인은 PNG 유지)
  5. 원본 PNG 삭제
  6. (선택) git add docs/ + commit + push origin master  → Cloudflare 자동 배포
"""

import argparse
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from config_loader import get_github_branch, PAPERS_DIR as _PAPERS_DIR, DOCS_DIR, PROJECT_ROOT, get_topic_dir
PAPERS_DIR = str(_PAPERS_DIR)
REPO = str(PROJECT_ROOT)


def ensure_gitignore():
    """text.md를 .gitignore에 추가."""
    gi_path = os.path.join(REPO, ".gitignore")
    existing = ""
    if os.path.exists(gi_path):
        with open(gi_path, "r", encoding="utf-8") as f:
            existing = f.read()

    additions = []
    for pattern in ["papers/*/text.md", "__pycache__/", "_update_force_checkpoint.json",
                     "_regen_*.py", "_update_force.log"]:
        if pattern not in existing:
            additions.append(pattern)

    if additions:
        with open(gi_path, "a", encoding="utf-8") as f:
            f.write("\n# Auto-generated by prepare_deploy.py\n")
            for p in additions:
                f.write(f"{p}\n")
        print(f"  .gitignore: added {len(additions)} patterns")
    else:
        print("  .gitignore: already up to date")


MIN_VALID_WEBP_BYTES = 200  # anything smaller is almost certainly corrupt


def convert_png_to_webp(png_path, quality=90):
    """PNG → WebP 변환. 성공 시 (원본크기, 변환크기, webp_path) 반환.

    실패하거나 손상된 WebP (너무 작음)의 경우 dangling webp 파일을
    정리하고 None 을 반환해, 뒤따르는 Step 5 의 PNG 삭제 로직이
    원본을 실수로 지우지 않도록 한다."""
    webp_path = png_path.replace(".png", ".webp")
    try:
        from PIL import Image
        img = Image.open(png_path)
        img.save(webp_path, "WEBP", quality=quality)
        orig_size = os.path.getsize(png_path)
        webp_size = os.path.getsize(webp_path)
        if webp_size < MIN_VALID_WEBP_BYTES:
            raise RuntimeError(
                f"WebP output too small ({webp_size} bytes, likely corrupt)")
        return orig_size, webp_size, webp_path
    except Exception as e:
        print(f"  ERR: {png_path}: {e}")
        # Clean up any partial/corrupt webp file so Step 5 does not
        # treat it as a successful conversion and delete the PNG.
        if os.path.exists(webp_path):
            try:
                os.remove(webp_path)
            except Exception as cleanup_err:
                print(f"    (failed to clean dangling webp: {cleanup_err})")
        return 0, 0, None


def update_html_refs(file_path, fig_only=False):
    """HTML/MD 파일에서 figure .png → .webp 참조 업데이트."""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    if fig_only:
        # 타임라인 PNG는 유지, figure 참조만 변환
        new_content = re.sub(r'(figures/[^"\']+)\.png', r'\1.webp', content)
    else:
        # 모든 .png → .webp (review.md, papers/*/index.html)
        new_content = re.sub(r'(figures/[^)\s"\']+)\.png', r'\1.webp', content)

    if new_content != content:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        return True
    return False


CF_BASE_URL = "https://paper-curation.jehyun-lee.workers.dev"
CF_PROBE_PATHS = ("/", "/humanoid/", "/physical-ai/", "/index.html")


def _verify_cloudflare(topic, timeout_s=300, interval_s=15):
    """Poll Cloudflare Worker endpoints until they all return 200 or timeout.

    We can't read a commit hash from response headers (Workers Static Assets
    don't expose one), so we only verify reachability + content size sanity.
    """
    import time as _time
    import urllib.request as _ur
    import urllib.error as _ue
    print(f"\n  [cf-verify] polling Cloudflare for ≤{timeout_s}s …")
    deadline = _time.time() + timeout_s
    last_status = {}
    while _time.time() < deadline:
        all_ok = True
        for path in CF_PROBE_PATHS:
            url = CF_BASE_URL + path
            try:
                req = _ur.Request(url, method="HEAD",
                                   headers={"User-Agent": "paper-curation/cf-verify"})
                resp = _ur.urlopen(req, timeout=10)
                code = resp.status
                size = resp.headers.get("content-length", "?")
                last_status[path] = (code, size)
                if code != 200:
                    all_ok = False
            except _ue.HTTPError as e:
                last_status[path] = (e.code, "?")
                all_ok = False
            except Exception as e:
                last_status[path] = ("err", str(e)[:60])
                all_ok = False
        if all_ok:
            print(f"  [cf-verify] all {len(CF_PROBE_PATHS)} endpoints 200 OK")
            for p, (c, s) in last_status.items():
                print(f"    {p}: {c} ({s} bytes)")
            return True
        _time.sleep(interval_s)
    print(f"  [cf-verify] TIMEOUT after {timeout_s}s — last status:")
    for p, (c, s) in last_status.items():
        print(f"    {p}: {c} ({s})")
    return False


def main():
    parser = argparse.ArgumentParser(description="Prepare for GitHub Pages deployment")
    parser.add_argument("--topic", default="ai4s")
    parser.add_argument("--quality", type=int, default=90, help="WebP quality (1-100)")
    parser.add_argument("--dry-run", action="store_true", help="Estimate only, no conversion")
    parser.add_argument("--push", action="store_true", help="Git add + commit + push after conversion")
    parser.add_argument("--topics", nargs="+", help="Only deploy these topics (exclude others from git add)")
    parser.add_argument("--workers", type=int, default=8, help="Parallel workers for conversion")
    args = parser.parse_args()

    topic_dir = str(get_topic_dir(args.topic))

    # Step 1: .gitignore
    print("Step 1: .gitignore")
    if not args.dry_run:
        ensure_gitignore()

    # Step 2: Find all figure PNGs
    print("\nStep 2: Finding PNGs...")
    png_files = []
    for slug in os.listdir(PAPERS_DIR):
        fig_dir = os.path.join(PAPERS_DIR, slug, "figures")
        if not os.path.isdir(fig_dir):
            continue
        for f in os.listdir(fig_dir):
            if f.endswith(".png"):
                png_files.append(os.path.join(fig_dir, f))

    total_png_size = sum(os.path.getsize(f) for f in png_files)
    print(f"  Found {len(png_files)} PNGs ({total_png_size / 1048576:.0f} MB)")

    if args.dry_run:
        # Estimate: sample 10 files
        sample = png_files[:10]
        sample_orig = sum(os.path.getsize(f) for f in sample)
        sample_webp = 0
        for f in sample:
            orig, webp, _ = convert_png_to_webp(f, args.quality)
            sample_webp += webp
            # Clean up test webp
            wp = f.replace(".png", ".webp")
            if os.path.exists(wp):
                os.remove(wp)
        if sample_orig > 0:
            ratio = sample_webp / sample_orig
            est_total = total_png_size * ratio / 1048576
            print(f"\n  Estimated WebP size: {est_total:.0f} MB ({ratio:.0%} of original)")
            print(f"  Savings: {(total_png_size / 1048576) - est_total:.0f} MB")
        return

    # Step 3: Convert PNGs to WebP (parallel)
    print(f"\nStep 3: Converting to WebP (quality={args.quality})...")
    total_orig = 0
    total_webp = 0
    converted = 0

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {executor.submit(convert_png_to_webp, f, args.quality): f for f in png_files}
        for future in futures:
            orig, webp, webp_path = future.result()
            if webp_path:
                total_orig += orig
                total_webp += webp
                converted += 1

    print(f"  Converted: {converted}/{len(png_files)}")
    print(f"  {total_orig / 1048576:.0f} MB → {total_webp / 1048576:.0f} MB "
          f"({total_webp / max(1, total_orig):.0%})")

    # Step 4: Update HTML/MD references (.png → .webp where .webp exists)
    # Always run regardless of PNG conversion count — HTML may have been
    # regenerated with .png refs after a previous PNG→WebP conversion.
    print("\nStep 4: Updating references...")
    updated = 0
    for slug in os.listdir(PAPERS_DIR):
        slug_dir = os.path.join(PAPERS_DIR, slug)
        if not os.path.isdir(slug_dir):
            continue
        # Only update if .webp figures actually exist
        fig_dir = os.path.join(slug_dir, "figures")
        has_webp = os.path.isdir(fig_dir) and any(f.endswith(".webp") for f in os.listdir(fig_dir))
        if not has_webp:
            continue
        for fname in ["index.html", "review.md"]:
            fpath = os.path.join(slug_dir, fname)
            if os.path.exists(fpath) and update_html_refs(fpath):
                updated += 1

    # Update topic index.html (figures only, keep timeline PNGs)
    topic_index = os.path.join(topic_dir, "index.html")
    if os.path.exists(topic_index) and update_html_refs(topic_index, fig_only=True):
        updated += 1

    print(f"  Updated: {updated} files")

    # Step 5: Delete original PNGs (only when WebP is verifiably good).
    # Double-defense against WebP-conversion races: we require the WebP
    # to actually exist AND to be at least MIN_VALID_WEBP_BYTES, which
    # catches cases where Pillow crashed halfway and left a tiny or
    # corrupt output. Any PNG preserved by this guard is logged so the
    # operator can investigate and retry.
    print("\nStep 5: Deleting original PNGs...")
    deleted = 0
    preserved = 0
    for png_path in png_files:
        webp_path = png_path.replace(".png", ".webp")
        if not os.path.exists(webp_path):
            preserved += 1
            print(f"  KEEP: {png_path} (no WebP)")
            continue
        webp_size = os.path.getsize(webp_path)
        if webp_size < MIN_VALID_WEBP_BYTES:
            preserved += 1
            print(f"  KEEP: {png_path} (WebP too small: {webp_size} bytes)")
            continue
        os.remove(png_path)
        deleted += 1
    print(f"  Deleted: {deleted} PNGs, Preserved: {preserved}")

    # Step 6: Strip API keys from HTML for deploy (local working tree restored after commit)
    print("\nStep 6: Stripping API keys from deployed HTML (local keys preserved)...")
    import re as _re
    _originals = {}  # Path -> original content, restored after push
    for html_path in DOCS_DIR.rglob("index.html"):
        text = html_path.read_text(encoding="utf-8")
        new_text = _re.sub(
            r'(const|let|var)\s+_ANTHROPIC_KEY\s*=\s*"sk-[^"]*"',
            r'\1 _ANTHROPIC_KEY = ""',
            text,
        )
        new_text = _re.sub(
            r'(const|let|var)\s+_OPENAI_KEY\s*=\s*"sk-[^"]*"',
            r'\1 _OPENAI_KEY = ""',
            new_text,
        )
        if new_text != text:
            _originals[html_path] = text
            html_path.write_text(new_text, encoding="utf-8")

    def _restore_originals():
        for p, orig in _originals.items():
            p.write_text(orig, encoding="utf-8")

    # Safety net: verify no residual API keys remain in any deployed HTML
    _leak_paths = [
        str(p) for p in DOCS_DIR.rglob("index.html")
        if _re.search(r'sk-(ant|proj)-[A-Za-z0-9_\-]{10,}', p.read_text(encoding="utf-8"))
    ]
    if _leak_paths:
        _restore_originals()
        print(f"  ABORT: API key still present in {len(_leak_paths)} files — refusing to commit:")
        for p in _leak_paths:
            print(f"    - {p}")
        sys.exit(1)
    print(f"  Stripped API keys from {len(_originals)} files (0 leaks remaining)")

    # Step 7: Commit docs/ changes and push to master (Cloudflare auto-deploys)
    try:
        if args.push:
            print("\nStep 7: Git commit + push to master (Cloudflare will auto-deploy)...")
            os.chdir(REPO)

            if args.topics:
                # Only add specified topics + shared resources (papers, index.html)
                subprocess.run(["git", "add", "docs/papers/", "docs/index.html"], check=True)
                for t in args.topics:
                    t_dir = os.path.join("docs", t)
                    if os.path.isdir(t_dir):
                        subprocess.run(["git", "add", t_dir], check=True)
                print(f"  Topics included: {', '.join(args.topics)}")
            else:
                subprocess.run(["git", "add", "docs/"], check=True)
            result = subprocess.run(
                ["git", "diff", "--cached", "--quiet"],
                capture_output=True
            )
            if result.returncode != 0:  # there are staged changes
                # Deploy-diff summary (visibility before irreversible push)
                diff_stat = subprocess.run(
                    ["git", "diff", "--cached", "--stat=160"],
                    capture_output=True, text=True, encoding="utf-8", errors="replace",
                )
                name_status = subprocess.run(
                    ["git", "diff", "--cached", "--name-status"],
                    capture_output=True, text=True, encoding="utf-8", errors="replace",
                )
                ns_lines = [l for l in (name_status.stdout or "").splitlines() if l.strip()]
                added = [l for l in ns_lines if l.startswith("A")]
                deleted = [l for l in ns_lines if l.startswith("D")]
                print(f"\n  Deploy diff: {len(ns_lines)} files changed "
                      f"(+{len(added)} new, -{len(deleted)} removed)")
                if deleted:
                    print("  Deletions (first 20):")
                    for l in deleted[:20]:
                        print(f"    {l}")
                    if len(deleted) > 20:
                        print(f"    ... +{len(deleted) - 20} more")
                # Tail of stat for context (last ~10 lines includes the summary row)
                stat_tail = "\n".join((diff_stat.stdout or "").splitlines()[-5:])
                if stat_tail:
                    print(f"  {stat_tail}")
                subprocess.run(["git", "commit", "-m",
                                f"Deploy: PNG→WebP conversion, {converted} figures, "
                                f"{total_orig // 1048576}→{total_webp // 1048576}MB\n\n"
                                f"Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"],
                               check=True)
                subprocess.run(["git", "push", "origin", "master"], check=True)
                print("  Pushed to master — Cloudflare Workers will auto-deploy")

                # ── Cloudflare deploy verification: poll known endpoints ──
                _verify_cloudflare(args.topic)
            else:
                print("  No staged changes to commit")
        else:
            print("\n(--push 없이 실행됨. git push는 수동으로)")
    finally:
        # Restore local working tree so Deep Research UI keeps working without rebuild
        _restore_originals()
        if _originals:
            print(f"  Restored {len(_originals)} local HTML files (API keys preserved for local dev)")

    print(f"\nDone! Total savings: {(total_orig - total_webp) / 1048576:.0f} MB")


if __name__ == "__main__":
    main()
